# Generated by Django 3.0.7 on 2022-02-27 03:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rede',
            name='redelocal',
        ),
        migrations.AddField(
            model_name='ip',
            name='redelocal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='feito',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP'),
        ),
        migrations.CreateModel(
            name='Diretorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)])),
                ('path', models.CharField(max_length=100)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
            ],
        ),
        migrations.CreateModel(
            name='DirbComandos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAgora', models.CharField(max_length=30)),
                ('feito', models.IntegerField(default=0)),
                ('comando', models.CharField(max_length=100)),
                ('porta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)])),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
