# Generated by Django 3.0.7 on 2022-02-27 03:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20220227_0341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirbComandos',
            new_name='FfufComandos',
        ),
    ]
