# Generated by Django 3.0.7 on 2022-02-27 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220227_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SistemaOperacional')),
            ],
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porta', models.IntegerField()),
                ('servico', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('versao', models.DecimalField(decimal_places=5, max_digits=10)),
                ('vulneravel', models.IntegerField()),
                ('tipo', models.IntegerField(default=0)),
                ('ativo', models.IntegerField(default=1)),
                ('descricao', models.CharField(max_length=50)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
            ],
        ),
        migrations.CreateModel(
            name='CVE_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CVE')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
            ],
        ),
    ]
