# Generated by Django 3.0.7 on 2022-02-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220227_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema_ip',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP'),
        ),
    ]
