# Generated by Django 3.0.7 on 2022-03-04 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pentest_pentest_rede'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretorios',
            name='http_code',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
    ]
