# Generated by Django 3.0.7 on 2022-03-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220305_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WhatWebIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
                ('whatweb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WhatWeb')),
            ],
        ),
    ]
