# Generated by Django 3.0.7 on 2022-03-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_whatweb_whatwebip'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWebComandos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feito', models.IntegerField(default=0)),
                ('comando', models.CharField(max_length=200)),
                ('diretorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diretorios')),
            ],
        ),
    ]
