# Generated by Django 3.0.7 on 2022-03-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_whatwebcomandos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatwebcomandos',
            old_name='comando',
            new_name='arquivo',
        ),
    ]
