# Generated by Django 3.0.7 on 2022-03-05 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220305_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
            ],
        ),
        migrations.CreateModel(
            name='spfDominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulneravel', models.IntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('Dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dominio')),
            ],
        ),
        migrations.CreateModel(
            name='inetNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipMaximo_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maximo', to='core.IP')),
                ('ipMinimo_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimo', to='core.IP')),
            ],
        ),
        migrations.CreateModel(
            name='dominioinetNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dominio')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inetNum')),
            ],
        ),
    ]
