# Generated by Django 3.0.7 on 2022-03-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dominio_dominioinetnum_inetnum_spfdominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('Dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dominio')),
            ],
        ),
    ]
