# Generated by Django 3.0.7 on 2022-03-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhaMsfConsole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
