# Generated by Django 3.0.7 on 2022-03-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_senhamsfconsole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('Dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dominio')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
            ],
        ),
    ]
