# Generated by Django 3.0.7 on 2022-03-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_exploit_payload_feito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exploit_payload',
            old_name='feito',
            new_name='tipo',
        ),
    ]
