# Generated by Django 3.0.7 on 2022-03-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220313_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParameteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100)),
                ('diretorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diretorios')),
            ],
        ),
    ]
