# Generated by Django 3.0.7 on 2022-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_queryparameteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryparameteres',
            name='valor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
