# Generated by Django 3.0.7 on 2022-03-13 08:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_queryparameteres_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlComandos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAgora', models.CharField(max_length=31)),
                ('feito', models.IntegerField(default=0)),
                ('comando', models.CharField(max_length=300)),
                ('porta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)])),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
