# Generated by Django 3.0.7 on 2022-03-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sqlcomandos'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryparameteres',
            name='vulneravel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sqlcomandos',
            name='diretorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Diretorios'),
            preserve_default=False,
        ),
    ]
