# Generated by Django 3.0.7 on 2022-03-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220313_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilidades_Definicoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='pentest',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
        migrations.CreateModel(
            name='Vulnerabilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('parametro', models.CharField(max_length=50)),
                ('CVSS', models.DecimalField(decimal_places=5, max_digits=10)),
                ('impacto', models.CharField(max_length=500)),
                ('recomendacao', models.CharField(max_length=500)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Porta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vulnerabilidades_Definicoes')),
            ],
        ),
    ]
