# Generated by Django 3.0.7 on 2022-03-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220316_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pentest',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/pentests'),
        ),
    ]
