# Generated by Django 3.0.7 on 2022-03-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220316_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=100)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pentest_Rede')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
            ],
        ),
    ]
