# Generated by Django 3.0.7 on 2022-03-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_etapas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve_ip',
            name='vulneravel',
            field=models.IntegerField(default=0),
        ),
    ]
