# Generated by Django 3.0.7 on 2022-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_cve_ip_vulneravel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilidades',
            name='tratada',
            field=models.IntegerField(default=0),
        ),
    ]
