# Generated by Django 3.0.7 on 2022-03-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_vulnerabilidades_tratada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema_ip',
            name='ativo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sistema_ip',
            name='probabilidade',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
