# Generated by Django 3.0.7 on 2022-03-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220322_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porta',
            name='versao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sistema_ip',
            name='ativo',
            field=models.IntegerField(default=0),
        ),
    ]
