# Generated by Django 3.0.7 on 2022-03-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220322_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve_ip',
            name='descricao',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
