# Generated by Django 3.0.7 on 2022-03-23 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220322_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlcomandos',
            name='dataAgora',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='Vulnerabilidades_Referencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=500)),
                ('Vulnerabilidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vulnerabilidades')),
            ],
        ),
    ]
