# Generated by Django 3.0.7 on 2022-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20220323_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='porta',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ip',
            name='ativo',
            field=models.CharField(max_length=30),
        ),
    ]
