# Generated by Django 3.0.7 on 2022-04-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20220413_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve_ip',
            name='titulo',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerabilidades',
            name='grau',
            field=models.CharField(default='VULNERABLE', max_length=30),
        ),
    ]
