# Generated by Django 3.0.7 on 2022-04-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20220422_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='vulnerabilidades',
            name='CVSS',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Hostname_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hostname')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IP')),
            ],
        ),
    ]
