# Generated by Django 3.0.7 on 2022-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20220428_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porta',
            name='dataAgora',
        ),
        migrations.AddField(
            model_name='porta',
            name='data_evento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
