# Generated by Django 3.2.10 on 2022-05-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_ataque_defesa_etapa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etapa',
            new_name='Checklist',
        ),
    ]
