# Generated by Django 3.2.10 on 2022-05-25 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_arquivo_bloco_de_notas_criptografada_hash_senha_cofre_senha_criptografada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistRede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checklist')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
