# Generated by Django 3.2.10 on 2022-05-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20220525_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistrede',
            name='level',
        ),
        migrations.RemoveField(
            model_name='checklistrede',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='checklistrede',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='checklistrede',
            name='tree_id',
        ),
    ]
