# Generated by Django 3.2.10 on 2022-05-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220525_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistrede',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
