# Generated by Django 3.2.10 on 2022-05-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_postagensforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagensforum',
            name='check',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
