# Generated by Django 3.2.10 on 2022-06-01 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0058_vulnerabilidades_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilidades_Tratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratada', models.IntegerField()),
                ('Vulnerabilidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vulnerabilidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
