# Generated by Django 3.2.10 on 2022-06-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_vulnerabilidades_tratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilidades_tratamento',
            name='data_evento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
